#index:
#    path: /
#    controller: App\Controller\DefaultController::index

adept_home:
  path: /
  controller: App\Controller\GeneralController::home

adept_registration:
  path: /inscription
  controller: App\Controller\SecurityController::registration

adept_logout:
  path: /deconnexion
  controller: App\Controller\SecurityController::logout

adept_menu:
  path: /menu
  controller: App\Controller\GeneralController::menu

adept_formations:
  path: /formations
  controller: App\Controller\GeneralController::formations

adept_analyze_choice:
  path: /analyze_choice
  controller: App\Controller\GeneralController::analyzeChoice

adept_tool_guide:
  path: /guide
  controller: App\Controller\GeneralController::guide

adept_ergonomics_tools_list:
  path: /tools
  controller: App\Controller\GeneralController::tools

adept_company_balance_sheet:
  path: /company
  controller: App\Controller\GeneralController::company

adept_settings:
  path: /settings
  controller: App\Controller\GeneralController::settings

adept_tool_NFX35109:
  path: /NFX35109
  controller: App\Controller\NFX35109Controller::NFX35109

adept_NFX35109_picture:
  path: /NFX35109/picture
  controller: App\Controller\NFX35109Controller::picture

adept_NFX35109_execution_conditions:
  path: /NFX35109/execution
  controller: App\Controller\NFX35109Controller::execution

adept_NFX35109_references_conditions:
  path: /NFX35109/references
  controller: App\Controller\NFX35109Controller::references

adept_NFX35109_constraints:
  path: /NFX35109/constraints
  controller: App\Controller\NFX35109Controller::constraints

adept_NFX35109_results:
  path: /NFX35109/results
  controller: App\Controller\NFX35109Controller::results

adept_tool_NIOSH:
  path: /NIOSH
  controller: App\Controller\GeneralController::NIOSH