#index:
#    path: /
#    controller: App\Controller\DefaultController::index

adept_home:
  path: /
  controller: App\Controller\GeneralController::home

adept_menu:
  path: /menu
  controller: App\Controller\GeneralController::menu

adept_formations:
  path: /formations
  controller: App\Controller\GeneralController::formations

adept_ergonomics_tools_list:
  path: /tools
  controller: App\Controller\GeneralController::tools

adept_company_balance_sheet:
  path: /company
  controller: App\Controller\GeneralController::company

adept_settings:
  path: /settings
  controller: App\Controller\GeneralController::settings

adept_tool_NFX35109:
  path: /NFX35109
  controller: App\Controller\NFX35109Controller::NFX35109

adept_tool_NIOSH:
  path: /NIOSH
  controller: App\Controller\GeneralController::NIOSH