#index:
#    path: /
#    controller: App\Controller\DefaultController::index

adept_home:
  path: /
  controller: App\Controller\GeneralController::home

adept_registration:
  path: /inscription
  controller: App\Controller\SecurityController::registration

adept_logout:
  path: /deconnexion
  controller: App\Controller\SecurityController::logout

adept_menu:
  path: /menu
  controller: App\Controller\GeneralController::menu

adept_formations:
  path: /formations
  controller: App\Controller\GeneralController::formations

adept_analyze_choice:
  path: /analyze_choice
  controller: App\Controller\GeneralController::analyzeChoice

adept_tool_guide:
  path: /guide/{id}
  controller: App\Controller\GeneralController::guide
  requirements:
    id:  \d+

adept_evaluator:
  path: /evaluator
  controller: App\Controller\GeneralController::evaluator

adept_ergonomics_tools_list:
  path: /tools
  controller: App\Controller\GeneralController::tools

adept_company_balance_sheet:
  path: /company
  controller: App\Controller\GeneralController::company

adept_settings:
  path: /settings
  controller: App\Controller\GeneralController::settings

adept_tool_NFX35109:
  path: /NFX35109/{id}
  controller: App\Controller\NFX35109Controller::NFX35109
  requirements:
    id:  \d+

adept_NFX35109_activity:
  path: /NFX35109/activity/{id}
  #controller: App\Controller\NFX35109Controller::activity
  controller: App\Controller\NFX35109Controller::nouvelEvaluateur
  requirements:
    id:  \d+

adept_NFX35109_picture:
  path: /NFX35109/picture/{id}
  #path: /NFX35109/picture/{id}/{id2}
  controller: App\Controller\NFX35109Controller::picture
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_operator:
  path: /NFX35109/operator/{id}
  #path: /NFX35109/operator/{id}/{id2}
  #controller: App\Controller\NFX35109Controller::operator
  controller: App\Controller\NFX35109Controller::nouvelOperateur
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_activity_detail:
  path: /NFX35109/activity/detail/{id}
  #path: /NFX35109/activity/detail/{id}/{id2}
  controller: App\Controller\NFX35109Controller::activityDetail
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_manutention_type:
  path: /NFX35109/handling_type/{id}
  #path: /NFX35109/handling_type/{id}/{id2}
  controller: App\Controller\NFX35109Controller::handlingType
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_handling_without_assistance:
  path: /NFX35109/handling_without_assistance/{id}
  #path: /NFX35109/handling_without_assistance/{id}/{id2}
  controller: App\Controller\NFX35109Controller::handlingWithoutAssistance
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_handling_without_assistance_charge_informations:
  path: /NFX35109/handling_without_assistance/new_charge/{id}
  #path: /NFX35109/handling_without_assistance/new_charge/{id}/{id2}
  controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceNewCharge
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_handling_without_assistance_execution_constraint:
  path: /NFX35109/handling_without_assistance/new_charge/execution_constraint/{id}/{id2}
  #path: /NFX35109/handling_without_assistance/new_charge/execution_constraint/{id}/{id2}/{id3}
  #controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceNewChargeConstraint
  controller: App\Controller\NFX35109Controller::listerContraintesExecution
  requirements:
    id:  \d+
    id2: \d+
    #id3: \d+

adept_NFX35109_handling_without_assistance_tonnage_frequence:
  path: /NFX35109/handling_without_assistance/tonnage_frequency/{id}
  #path: /NFX35109/handling_without_assistance/tonnage_frequency/{id}/{id2}
  controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceTonnageFrequency
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_handling_without_assistance_constraints:
  path: /NFX35109/handling_without_assistance/constraints/{id}
  #path: /NFX35109/handling_without_assistance/constraints/{id}/{id2}
  #controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceNewConstraints
  controller: App\Controller\NFX35109Controller::listerContraintes
  requirements:
    id:  \d+
    #id2: \d+

adept_NFX35109_handling_without_assistance_resume:
  path: /NFX35109/handling_without_assistance/resume/{id}
  controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceResume
  requirements:
    id:  \d+

#Résumé de la charge dans une activité de manutention manuelle sans aide à la manutention.
adept_NFX35109_handling_without_assistance_resume_charge:
  path: /NFX35109/handling_without_assistance/resume/charge/{id}/{id2}
  controller: App\Controller\NFX35109Controller::handlingWithoutAssistanceResumeCharge
  requirements:
    id:  \d+
    id2: \d+

adept_NFX35109_handling_with_assistance:
    path: /NFX35109/handling_with_assistance
    controller: App\Controller\NFX35109Controller::handlingWithAssistance

adept_NFX35109_execution_conditions:
  path: /NFX35109/execution
  controller: App\Controller\NFX35109Controller::execution

adept_NFX35109_references_conditions:
  path: /NFX35109/references
  controller: App\Controller\NFX35109Controller::references

adept_NFX35109_constraints:
  path: /NFX35109/constraints
  controller: App\Controller\NFX35109Controller::constraints

adept_NFX35109_results:
  path: /NFX35109/results
  controller: App\Controller\NFX35109Controller::results

adept_tool_ED6161:
  path: /ED6161
  controller: App\Controller\GeneralController::ED6161

adept_tool_NIOSH:
  path: /NIOSH
  controller: App\Controller\GeneralController::NIOSH